"""initial schema

Revision ID: d3e5a7599d6b
Revises: 
Create Date: 2025-02-20 09:16:20.815013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e5a7599d6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice', 'tax_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=4, scale=2),
               existing_nullable=False)
    op.drop_constraint('invoice_company_details_id_fkey', 'invoice', type_='foreignkey')
    op.create_foreign_key(None, 'invoice', 'company_details', ['company_details_id'], ['id'], ondelete='SET NULL')
    op.alter_column('invoice_item', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('invoice_item', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.drop_constraint('invoice_item_invoice_id_fkey', 'invoice_item', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_item', 'invoice', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_item', type_='foreignkey')
    op.create_foreign_key('invoice_item_invoice_id_fkey', 'invoice_item', 'invoice', ['invoice_id'], ['id'])
    op.alter_column('invoice_item', 'subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoice_item', 'unit_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.create_foreign_key('invoice_company_details_id_fkey', 'invoice', 'company_details', ['company_details_id'], ['id'])
    op.alter_column('invoice', 'tax_rate',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoice', 'tax_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('invoice', 'total_amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
